version: "3.5"

services:
  # Services
  consignment:
    restart: always
    build: ./shippy-service-consignment
    depends_on:
      - datastore
      - vessel
    links:
      - datastore
    ports:
      - 50051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  vessel:
    restart: always
    build: ./shippy-service-vessel
    depends_on:
      - datastore
    ports:
      - 50052:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  user:
    restart: always
    build: ./shippy-service-user
    depends_on:
      - database
    ports:
      - 50053:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "database"
      DB_USER: "admin"
      DB_PASSWORD: "password"
      DB_NAME: "postgres"

  #command
  cli:
    build: ./shippy-cli-consignment

  user-cli:
    build: ./shippy-cli-user

  database:
    image: postgres:alpine
    container_name: "database"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
    ports:
      - 5432:5432

  #database
  datastore:
    image: mongo
    container_name: "datastore"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null
